apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    server {
      listen 80;
      server_name htmlwebsite.com;
      location / {
        proxy_pass http://html-service:80;
      }
    }